---
##
# set correct gateway
##
- name: ensure the gateway is correct
  shell:
    "ip r d default && ip r a default via {{ net_config['admin'].gateway }}"
  when: "'nodes' in group_names"

##
# set correct resolv.conf
##

- name: set resolv.conf
  copy:
    content: "nameserver {{ net_config['admin'].dns }}"
    dest: /etc/resolv.conf
##
# install basic packages
##
- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: install packages
  import_tasks: install_DEBIAN.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install docker pip packages
  pip:
    name: docker
    state: latest
##
# Prepare modules
##
- name: configure modules
  lineinfile:
    dest: /etc/modules
    state: present
    create: 'yes'
    line: "8021q"
  when: "'nodes' in group_names"
- name: add modules
  modprobe:
    name: 8021q
    state: present
  when: "'nodes' in group_names"
- name: ensure glean rules are removed
  file:
    path: "/etc/udev/rules.d/99-glean.rules"
    state: absent
  when: "'nodes' in group_names"

##
# Get remote network data
##
- name: get nodes as a dict
  set_fact:
    nodes_dict: "{{ nodes | nodes_as_dict() }}"
  when: "'nodes' in group_names"
- name: get bridges to configure
  set_fact:
    node_netw: >
      {{ inventory_hostname |
      get_networks(hostvars, network_profiles, xci.nodes_roles) }}
  when: "'nodes' in group_names"
- name: get srv_macs
  set_fact:
    srv_macs:
      "{{ inventory_hostname | target_interfaces(hostvars, nodes_dict) }}"
  when: "'nodes' in group_names"
- debug:
    var: srv_macs
  when: "'nodes' in group_names"
- name: get mac2intf
  set_fact:
    macs: "{{ inventory_hostname | mac2intf(hostvars, nodes_dict) }}"
  when: "'nodes' in group_names"
- debug:
    var: macs
  when: "'nodes' in group_names"
- name: get mgmt interface
  set_fact:
    mgmt_intf: "{{ macs[srv_macs[net_config['admin'].interface]] }}"
  when: "'nodes' in group_names"
- debug:
    var: mgmt_intf
  when: "'nodes' in group_names"
- name: shortcut for network mapping
  set_fact:
    nmap: "{{ xci.network_mapping }}"
  when: "'nodes' in group_names"

##
# Prepare network
##
- name: ensure interfaces.d folder is empty
  file:
    path: "/etc/network/interfaces.d"
    state: "{{ item }}"
  with_items:
    - absent
    - directory
  when: "'nodes' in group_names"
- name: ensure interfaces file is updated
  template:
    src: "templates/interfaces.j2"
    dest: "/etc/network/interfaces"
  when: "'nodes' in group_names"
- name: restart all interfaces
  shell: "ifdown --exclude=lo -a && ifup --exclude=lo -a && sleep 5"
  when: "'nodes' in group_names"


##
# Decide to use ceph as backend or not
##
- include_tasks: ceph.yaml
  when: xci.ceph_mapping is defined

- include_tasks: no_ceph.yaml
  when: xci.ceph_mapping is not defined

##
# Restart services
##
- name: restart NTP service
  systemd:
    name: ntp
    state: restarted
    daemon_reload: 'yes'
    no_block: true

##
# Purge setuptools for a better Kolla install
# TODO: check if needed
##
- name: remove setuptools
  pip:
    name: setuptools
    state: absent


##
#
##
- name: add infra domain in resolv.conf
  lineinfile:
    regexp: '^search'
    line: "search {{ xci.infra_domain }}"
    path: /etc/resolv.conf

- name: add host and fqdn in resolv.conf
  lineinfile:
    regexp: ' {{ ansible_hostname }}'
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.{{ xci.infra_domain }} {{ ansible_hostname }}"
    path: /etc/hosts

- include_tasks: ceph.yaml
  when: xci.ceph_mapping is defined