---
before_script:
  - apt-get update -qq && apt-get install -y -qq yamllint

syntax_checking:
    tags:
        - ubuntu
        - docker
    script:
        - yamllint config_sources/labs/orange/*y?ml
