---
stages:
  - test
  - deploy
  - check

variables:
  pod: pod1
  os_version: stable/pike
  target_folder: /opt/bosa
  scenario: os-nosdn-nofeature-ha

syntax_checking:
  stage: test
  image: dockerproxy-iva.si.francetelecom.fr/debian:latest
  tags:
    - shared
    - docker
    - innovation
  script:
    - apt-get update -qq
    - apt-get install -y -qq yamllint python3-pkg-resources
    - yamllint *.y?ml
    - yamllint vars/
    - yamllint roles/*/tasks/*.y?ml

# Deploy
deploy:
  stage: deploy
  tags:
    - sina
  script:
    - cd vars
    - git archive --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git HEAD:config ${pod}.yaml | tar -x
    - git archive --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git HEAD:config idf-${pod}.yaml | tar -x
    - perl -i -pe "s!stable/ocata!$os_version!" defaults.yaml
    - ln -s ${pod}.yaml pdf.yaml
    - ln -s idf-${pod}.yaml idf.yaml
    - cd ..
    - rsync --cvs-exclude -e ssh -avz  --delete-after . ${pod}.opnfv.fr:${target_folder}
    - ssh ${pod}.opnfv.fr "cd /opt/bosa; sudo ./run.sh orange ${pod}"
    - date=$(date +%Y-%m-%d)
    - os_version=$(echo ${os_version} | perl -pe 's!/!_!')
    - rm ansible-role-requirements*
    - scp ${pod}.opnfv.fr:/opt/openstack-ansible/ansible-role-requirements.yml ansible-role-requirements${os_version}_${date}.yml
  artifacts:
    paths:
      - ansible-role-requirements${os_version}_*.yml

# Run functest
trigger_check:
  stage: check
  script:
    - "curl -X POST\
      -F token=${functest_token}\
      -F ref={functest_ref_name}\
      -F 'variables[pod]=${pod}'\
      -F 'variables[scenario]=${scenario}'\
      https://gitlab.forge.orange-labs.fr/api/v4/projects/1674/trigger/pipeline"
