---
stages:
  - syntax_checking
  - deploy

syntax_checking:
  stage: syntax_checking
  image: dockerproxy-iva.si.francetelecom.fr/debian:latest
  tags:
    - shared
    - docker
    - innovation
  script:
    - apt-get update -qq
    - apt-get install -y -qq yamllint python3-pkg-resources
    - yamllint *.y?ml
    - yamllint vars/
    - yamllint roles/*/tasks/*.y?ml


### A travailler
deploy:
  stage: deploy
  tags:
    - sina
  variables:
    pod: pod1
    os_version: stable/pike
    target_folder: /opt/bosa
    terrahouat_raw:
      https://gitlab.forge.orange-labs.fr/opnfv/TerraHouat/raw/master
  script:
    - cd vars
    - git archive --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git HEAD:config ${pod}.yaml | tar -x
    - git archive --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git HEAD:config idf-${pod}.yaml | tar -x
    - perl -i -pe "s!stable/ocata!$os_version!"
    - ln -s ${pod}.yaml pdf.yaml
    - ln -s idf-${pod}.yaml idf.yaml
    - cd ..
    - rsync --cvs-exclude -e ssh -avz  --delete-after . ${pod}.opnfv.fr:${target_folder}
    - ssh ${pod}.opnfv.fr "cd /opt/bosa; sudo ./run.sh orange ${pod}"
