---
stages:
  - test
  - deploy
  - check

variables:
  os_version: stable/pike
  target_folder: /opt/bolla
  scenario: os-nosdn-nofeature-ha

.syntax_checking: &syntax_docker
  stage: test
  tags:
    - shared
    - docker
    - innovation

yaml_checking:
  image: dockerproxy-iva.si.francetelecom.fr/sdesbure/yamllint:latest
  script:
    - yamllint .gitlab-ci.yml
    - yamllint *.y?ml
    - yamllint vars/*.y?ml
    - yamllint roles/*/tasks/*.y?ml
  <<: *syntax_docker

ansible_linting:
  image: dockerproxy-iva.si.francetelecom.fr/sdesbure/ansible-lint:latest
  script:
    - ansible-lint -x ANSIBLE0010,ANSIBLE0013 opnfv-*.yaml
  <<: *syntax_docker

# Deploy
.deploy_pod: &deploy_pod
  stage: deploy
  tags:
    - sina
    - shell
  only:
    - master
  script:
    - ssh ${pod}.opnfv.fr "sudo mkdir -p ${target_folder} ;
                           sudo chown -R ubuntu.ubuntu ${target_folder}"
    - cd vars
    - "git archive \
       --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git \
       HEAD:config \
       ${pod}.yaml \
       | tar -x"
    - "git archive \
       --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git \
       HEAD:config \
       idf-${pod}.yaml \
       | tar -x"
    - "git archive \
       --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git \
       HEAD:certificats \
       certificats-${pod}.yaml \
       | tar -x"
    - ln -s ${pod}.yaml pdf.yaml
    - ln -s idf-${pod}.yaml idf.yaml
    - ln -s certificats-${pod}.yaml certificates.yaml
    - ln -s rndc-${pod}.yaml rndc.yaml
    - cd ..
    - "rsync --cvs-exclude -e ssh -avz  \
      --delete-after . \
      ${pod}.opnfv.fr:${target_folder}"
    - ssh ${pod}.opnfv.fr \
      "echo ${ANSIBLE_VAULT_PASSWORD} > ${target_folder}/.vault_pass.txt"
    - ssh ${pod}.opnfv.fr "cd ${target_folder}; \
      target_folder=${target_folder} sudo -E ./run.sh"
    - ./trigger_functest.sh
    - ./trigger_rancher.sh
  after_script:
    - ssh ${pod}.opnfv.fr "rm ${target_folder}/.vault_pass.txt || true"
  artifacts:
    paths:
      - ansible-role-requirements_*.yml

deploy_pod1:
  variables:
    pod: pod1
  environment:
    name: pod1
    url: https://osa.pod1.opnfv.fr/
  when: manual
  <<: *deploy_pod

deploy_pod2:
  variables:
    pod: pod2
    scenario: os-nosdn-nofeature-noha
  environment:
    name: pod2
    url: https://osa.pod2.opnfv.fr/
  when: manual
  <<: *deploy_pod

deploy_pod4:
  variables:
    pod: pod4
    scenario: os-nosdn-nofeature-ha
  environment:
    name: pod4
    url: https://osa.pod4.opnfv.fr/
  when: manual
  <<: *deploy_pod
