---
before_script:
  - apt-get update -qq && apt-get install -y -qq yamllint

syntax_checking:
    image: dockerproxy-iva.si.francetelecom.fr/debian:latest
    tags:
        - shared
        - docker
    script:
        - yamllint config_sources/labs/orange/*y?ml
