---
- hosts: localhost
  connection: local
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf_orange-pod1.yaml"
    - "vars/pdf_orange-pod1.yaml"
  tasks:
    ##
    # Check syntax
    ##
    - name: Setup hosts
      shell: "openstack-ansible setup-hosts.yml"
      args:
        chdir: "{{ osa_path }}/playbooks/"
