---
- hosts: nodes
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf.yaml"
    - "vars/pdf.yaml"
    - "{{ bifrost_path }}/playbooks/roles/
      bifrost-deploy-nodes-dynamic/defaults/main.yml"
  gather_facts: 'no'
  roles:
    - nodes_wait_for

- hosts: nodes
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf.yaml"
    - "vars/pdf.yaml"
  roles:
    - nodes_prepare
