---
- hosts: localhost
  become: true
  vars_files:
    - "vars/defaults.yaml"
    - "vars/pdf_orange-pod1.yaml"
  vars:
    target: '/tmp/bosa/tpl_pdf/'
  tasks:
    ##
    # WIP local test of jinja templates
    ##
    # - name: set bifrost inventory
    #   template:
    #     src: "templates_pdf/bifrost_inventory.json.j2"
    #     dest: "{{ target }}/bifrost_inventory.json"
#     - name: set bifrost {{ item }} inventory
#       template:
#         src: "templates_pdf/bifrost_inventory.json.j2"
#         dest: "{{ target }}/bifrost_inventory/{{ item }}.json"
#       with_items: "{{ pod.nodes }}"
#     - name: prepare ssh config file
#       template:
#         src: "templates_pdf/ssh_config.j2"
#         dest: "{{ target }}/config"
#     - name: set ansible node inventory
#       template:
#         src: "templates_pdf/ansible_inventory.j2"
#         dest: "{{ target }}/ansible_inventory"
#     - name: copy bifrost target vars
#       template:
#         dest: "{{ target }}/target"
#         src: "templates_pdf/target.j2"
#     - name: copy bifrost baremetal vars
#       template:
#         dest: "{{ target }}/baremetal"
#         src: "templates_pdf/baremetal.j2"
#     - name: set openstack_user_config.yml
#       template:
#         src: "templates_pdf/openstack_user_config.yml.prod.j2"
#         dest: "{{ target }}/openstack_user_config.yml"
#
# - hosts: nodes
#   vars_files:
#     - "vars/pods.yaml"
#     - "vars/servers.yaml"
#     - "vars/defaults.yaml"
#   tasks:
#     ##
#     # Get mac2intf list1
#     ##
#     - name: get bridges to configure
#       set_fact:
#         bridges: "{{ inventory_hostname | get_bridges(hostvars, network_profiles, pod) }}"
#     - name: get srv_macs
#       set_fact:
#         srv_macs: "{{ inventory_hostname | target_interfaces(hostvars, servers) }}"
#     - name: get mac2intf
#       set_fact:
#         macs: "{{ inventory_hostname | mac2intf(hostvars, servers) }}"
#     - name: get mgmt interface
#       set_fact:
#         mgmt_intf: "{{ macs[srv_macs[pod.net_config['br-mgmt'].interface]] }}"
#     - name: get mgmt network prefix
#       set_fact:
#         mgmt_net_p: "{{ pod.net_config['br-mgmt'].network.split('.')[0:-1]|join('.') }}"
#
#
#     - name: ensure interfaces file is updated
#       template:
#         src: "templates_pdf/interfaces.j2"
#         dest: "/etc/network/interfaces"
