---
# openstack ansible must have been prepared first in order to be able to
# retrieve the inventory file (located in
# `/etc/openstack_deploy/openstack_inventory.json`)
- hosts: haproxy_all
  become: true
  vars_files:
    - "vars/rndc.yaml"
  roles:
    - bind_install
- hosts: designate_container
  become: true
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf.yaml"
    - "vars/rndc.yaml"
  roles:
    - designate_prepare

- hosts: localhost
  connection: local
  become: true
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf.yaml"
    - "vars/rndc.yaml"
  roles:
    - designate_configure
