net_config:
    br-mgmt:
        interface: 0
        vlan: 0
        network: 10.1.0.0
        mask: 24
        gateway: 10.1.0.1
        dns: 10.1.0.1
    br-storage:
        interface: 1
        vlan: 2051
        network: 10.1.1.0
        mask: 24
    br-vxlan:
        interface: 2
        vlan: 0
        network: 10.1.3.0
        mask: 24
    br-vlan:
        interface: 1
        vlan: 2052
        network: 10.1.2.0
        mask: 24

profiles:
    controller:
        - br-mgmt
    storage:
        - br-mgmt
        - br-storage
    network:
        - br-mgmt
        - br-vxlan
        - br-vlan
    compute:
        - br-mgmt
        - br-vxlan
        - br-vlan

nodes:
    server02:
        id: 0
        type: [ compute, storage ]
        macs:
            - 94:57:a5:52:f1:80
            - 94:57:a5:52:f1:81
            - 94:57:a5:52:f1:82
    server03:
        id: 1
        type: [ compute, storage ]
        macs:
            - 94:57:a5:52:63:b0
            - 94:57:a5:52:63:b1
            - 94:57:a5:52:63:b2
    server04:
        id: 2
        type: [ controller ]
        macs:
            - 94:57:a5:52:c9:48
            - 94:57:a5:52:c9:49
            - 94:57:a5:52:c9:4a
    server09:
        id: 3
        type: [ controller ]
        macs:
            - 94:57:a5:52:53:7c
            - 94:57:a5:52:53:7d
            - 94:57:a5:52:53:7e
    server11:
        id: 4
        type: [ controller ]
        macs:
            - 94:57:a5:52:c1:d8
            - 94:57:a5:52:c1:d9
            - 94:57:a5:52:c1:da
