---
##
# Clean and install packages get Bifrost sources
##
- name: install packages
  import_tasks: install_DEBIAN.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

##
# Start registry
##
- name: start registry
  docker_container:
    name: registry
    image: registry:2
    ports:
      - 5000:5000
    restart_policy: always
    env:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    state: started