---
##
# Correct image gen and remove old images
##
- name: correct bifrost image generation
  lineinfile:
    path: "{{ bifrost_path }}/playbooks/install.yaml"
    regexp: '^(.*) serial-console(.*)$'
    line: '\1 enable-serial-console\2'
    backrefs: 'yes'
- name: Remove old image
  file:
    path: "/httpboot/deployment_image*"
    state: absent
