---
##
# Setup bifrost ansible environment
##
- name: setup bifrost ansible environment
  shell: "./scripts/env-setup.sh"
  args:
    chdir: "{{ bifrost_path }}/"
  environment:
    VENV: "{{ bifrost_venv_folder if bifrost_enable_venv else '' }}"
##
# Setup bifrost wrapper to enable or not virtualenv
##
- name: Set bifrost-ansible wrapper
  template:
    dest: "/usr/local/bin/bifrost-ansible"
    src: "templates/bifrost-ansible.j2"
    mode: 0500
- name: Set bifrost-pip wrapper
  template:
    dest: "/usr/local/bin/bifrost-pip"
    src: "templates/bifrost-pip.j2"
    mode: 0500
