---
- name: Clean old bifrost
  file:
    path: "{{ bifrost_path }}"
    state: absent
- name: "clone bifrost {{bifrost_branch}}"
  git:
    repo: "{{ bifrost_url }}"
    dest: "{{ bifrost_path }}"
    version: "{{ bifrost_branch }}"
