---
- name: set reconfigure to no
  set_fact:
    need_reconfigure_designate: "no"

- name: get nodes ips
  set_fact:
    nodes_ip: >
      {{ nodes |
      node_ips(net_config[xci.network_mapping['br-mgmt']].network,
               ip_shift) }}

- debug: msg="{{ groups['designate-backend-bind9'] }}"

- debug: msg="{{ nodes_ip[item]['ip'] }}"
  with_items: "{{ groups['designate-backend-bind9'] }}"

- name: generate bind_servers list
  set_fact:
    bind_servers: "{{ bind_servers|default([]) +[{'name': item, 'ip': nodes_ip[item]['ip'] }]}}"
  with_items: "{{ groups['designate-backend-bind9'] }}"

- name: generate mdns_servers list
  set_fact:
    mdns_servers_ip: "{{ mdns_servers_ip|default([]) +[ nodes_ip[item]['ip'] ]}}"
  with_items: "{{ groups['designate-mdns'] }}"

- debug: msg="bind_servers"
- debug: msg="{{ bind_servers }}"

- name: generate specific named conf per server
  include_tasks: generate_named_conf.yaml
  with_items: "{{ bind_servers }}"

- name: create default zone
  os_zone:
    state: present
    name: "{{ xci.pod_name.split('.')[-1] }}.{{ dns_domain }}."
    email: test@example.net
    description: Default zone for openstack
    ttl: 3600
  register: zone

- name: retrieve zone id
  set_fact:
    zone_id: "{{ zone.zone.id }}"

- name: "generate designate-sink specific add to conf"
  template:
    src: designate-sink.conf.j2
    dest: "{{ kolla_etc_path }}/config/designate/designate-sink.conf"
  notify: reconfigure designate