---
- name: Install list of packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: retrieve linux type
  set_fact:
    distri: "{{ ansible_distribution.lower() }}"

- name: retrieve docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ distri }}/gpg"
    id: 0EBFCD88
    state: present

- name: retrieve linux release
  set_fact:
    release: "{{ ansible_distribution_release.lower() }}"

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ distri }} {{ release }} stable"
    state: present

- name: install docker
  apt:
    update_cache: yes
    name: docker-ce

- name: add login user to docker group
  user: name={{ansible_user}} groups=docker append=yes

- name: install pip
  easy_install:
    name: pip
    state: latest

- name: install docker py
  pip:
    name: docker-py
    state: present