---
##
# Clean
##
- name: Clean old files and folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/usr/local/bin/bifrost*'
    - '/usr/local/bin/ironic*'
    - '/opt/ansible-runtime/'
    - '/opt/bifrost/'
    - '/opt/kolla-ansible/'
    - '/opt/kolla/'
    - '/opt/stack/'
    - '/etc/bosa/'
    - '/etc/openstack_deploy/'
    - '/etc/kolla'

- name: clean Bifrost DB
  mysql_db:
    name: ironic
    state: absent
    login_user: ironic
    login_password: "{{ ironic_db_password }}"
  ignore_errors: 'yes'
##
# Gen SSH keys if not exists
##
- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

##
# Clean and install packages get Bifrost sources
##
- name: install packages
  import_tasks: install_DEBIAN.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

##
# Add registry host in inventory
##

- name: add registry host in inventory
  add_host:
    name: registryhost
    ansible_ssh_host: "{{ xci.registry }}"

##
# Create an OPNFV user
##
- name: create opnfv group
  group:
    name: "{{ opnfv_user }}"
    state: present
- name: create opnfv user
  user:
    name: "{{ opnfv_user }}"
    comment: "OPNFV ops"
    group: "{{ opnfv_user }}"
    groups: admin
    generate_ssh_key: "yes"
- name: copy certs
  copy:
    src: "/root/.ssh/{{ item }}"
    dest: "/home/{{ opnfv_user }}/.ssh/{{ item }}"
    owner: "{{ opnfv_user }}"
    group: "{{ opnfv_user }}"
  with_items:
    - 'id_rsa'
    - 'id_rsa.pub'
