---
##
# wait for nodes to be reachable after bifrost deploy reboot
##
- name: wait for nodes to be reachable
  include_tasks: wait.yaml
  ignore_errors: yes
- name: restart node if it is unreachable
  include_tasks: restart.yaml
  when: ping.rc != 0
- name: wait - again - for restarted node
  include_tasks: wait.yaml
